name: WeightApp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  flutter_launcher_icons: ^0.8.0
  firebase_auth: ^0.20.1
  flutter_signin_button: ^1.0.0
  firebase_core: ^0.7.0
  google_sign_in: ^4.5.9
  flushbar: ^1.10.4
  convex_bottom_bar: ^2.7.1+2
  cloud_firestore: ^0.16.0+1
  flutter_swiper: 1.1.6
  fluttertoast: ^4.0.1
  firebase_database:
  firebase_storage:
  image_picker: ^0.6.7+14
  carousel_slider: ^2.3.1
  flutter_screenutil: ^1.0.2
  cached_network_image:
#  image_picker: ^0.6.5+3
  simple_animations: ^1.3.3
  shared_preferences: ^0.5.3+4
  flashy_tab_bar: ^0.0.3
#  just_audio: ^0.3.4
  audio_service: ^0.13.0
  audioplayers: ^0.15.1
  flutter_exoplayer: ^0.5.5
  flutter_downloader: ^1.0.5
  permission_handler: ^5.1.0+2
#  cached_video_player: ^1.0.3
#  cachedflickvideoplayer:
  visibility_detector:
  intl:
  connectivity_plus: ^0.8.1
  firebase_messaging: ^6.0.16
  wave: ^0.2.1
  #  audioplayers: ^0.17.4
  #  flutter_radio_player: ^1.0.7
  #  music_player: ^0.1.5
  #  just_audio_background:
  #  flutter_widget_from_html:
  readmore: ^2.1.0
  sqflite: any
  path_provider:
  #  shared_preferences: 0.4.3
  share: 0.5.3
  #  flutter_localizations:
  #   sdk: flutter
  dots_indicator: ^1.0.0
  youtube_player_flutter: ^6.0.0
  firebase_dynamic_links:
  flutter_spinkit: ^4.1.2+1
  file_picker: ^1.1.1
  multi_image_picker:
  provider: ^4.3.2+2
#  flutterwave: ^0.0.2-dev.4
  flutter_paystack: ^1.0.4+1
  url_launcher: ^5.5.0
  flutter_launch: "^0.3.0"
  font_awesome_flutter:
  percent_indicator: ^2.1.9+1
  map_launcher: ^0.5.0
  shimmer: ^2.0.0
#  flutter_widget_from_html:









  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.3

flutter_icons:
  image_path: "assets/images/victory_chapel.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/bible-data.db


  fonts:
    - family: Nunito
      fonts:
        - asset: assets/font/nunito_regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/font/rubik_regular.ttf
    - family: Abel
      fonts:
        - asset: assets/font/Abel-Regular.ttf


